"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-12 21:11:42.922150

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("competition_type", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition")),
        sa.UniqueConstraint("slug", name=op.f("uq_competition_slug")),
    )
    op.create_table(
        "data_source",
        sa.Column("source_id", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("homepage_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_data_source")),
    )
    op.create_table(
        "ingestion_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.String(length=50), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_touched", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run")),
    )
    op.create_index(
        op.f("ix_ingestion_run_data_source_id"), "ingestion_run", ["data_source_id"], unique=False
    )
    op.create_table(
        "model_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("family", sa.String(length=100), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=False),
        sa.Column("hyperparams", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_path", sa.String(length=500), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_promoted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_version")),
        sa.UniqueConstraint("name", name=op.f("uq_model_version_name")),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=10), nullable=True),
        sa.Column("position", sa.String(length=10), nullable=True),
        sa.Column("preferred_foot", sa.String(length=10), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player")),
    )
    op.create_table(
        "referee",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("cards_per_game", sa.Float(), nullable=True),
        sa.Column("penalties_per_game", sa.Float(), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referee")),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=False),
        sa.Column("team_type", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
        sa.UniqueConstraint("name", name=op.f("uq_team_name")),
    )
    op.create_table(
        "venue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("altitude_m", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue")),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competition.id"],
            name=op.f("fk_season_competition_id_competition"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season")),
        sa.UniqueConstraint("competition_id", "label", name=op.f("uq_season_competition_id")),
    )
    op.create_index(op.f("ix_season_competition_id"), "season", ["competition_id"], unique=False)
    op.create_table(
        "match",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=False),
        sa.Column("kickoff_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=True),
        sa.Column("referee_id", sa.UUID(), nullable=True),
        sa.Column("is_home_neutral", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("home_corners", sa.Integer(), nullable=True),
        sa.Column("away_corners", sa.Integer(), nullable=True),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["team.id"],
            name=op.f("fk_match_away_team_id_team"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["team.id"],
            name=op.f("fk_match_home_team_id_team"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["referee_id"],
            ["referee.id"],
            name=op.f("fk_match_referee_id_referee"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["season.id"], name=op.f("fk_match_season_id_season"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venue.id"], name=op.f("fk_match_venue_id_venue"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
    )
    op.create_index("ix_match_kickoff_utc", "match", ["kickoff_utc"], unique=False)
    op.create_index("ix_match_season_id", "match", ["season_id"], unique=False)
    op.create_table(
        "feature_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("code_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_feature_snapshot_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshot")),
    )
    op.create_index(
        "ix_feature_snapshot_match",
        "feature_snapshot",
        ["match_id", "snapshot_taken_at"],
        unique=False,
    )
    op.create_table(
        "match_lineup",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("formation", sa.String(length=20), nullable=True),
        sa.Column("players", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_match_lineup_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_match_lineup_team_id_team"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_lineup")),
    )
    op.create_index(op.f("ix_match_lineup_match_id"), "match_lineup", ["match_id"], unique=False)
    op.create_table(
        "prediction",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("market", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("prob", sa.Float(), nullable=False),
        sa.Column("ci_low", sa.Float(), nullable=False),
        sa.Column("ci_high", sa.Float(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("feature_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ci_low <= ci_high", name=op.f("ck_prediction_ci_ordered")),
        sa.CheckConstraint("prob >= 0.0 AND prob <= 1.0", name=op.f("ck_prediction_prob_range")),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshot.id"],
            name=op.f("fk_prediction_feature_snapshot_id_feature_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_prediction_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
            name=op.f("fk_prediction_model_version_id_model_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction")),
        sa.UniqueConstraint(
            "match_id",
            "market",
            "outcome",
            "model_version_id",
            "feature_snapshot_id",
            name=op.f("uq_prediction_match_id"),
        ),
    )
    op.create_index(
        "ix_prediction_match_market", "prediction", ["match_id", "market"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prediction_match_market", table_name="prediction")
    op.drop_table("prediction")
    op.drop_index(op.f("ix_match_lineup_match_id"), table_name="match_lineup")
    op.drop_table("match_lineup")
    op.drop_index("ix_feature_snapshot_match", table_name="feature_snapshot")
    op.drop_table("feature_snapshot")
    op.drop_index("ix_match_season_id", table_name="match")
    op.drop_index("ix_match_kickoff_utc", table_name="match")
    op.drop_table("match")
    op.drop_index(op.f("ix_season_competition_id"), table_name="season")
    op.drop_table("season")
    op.drop_table("venue")
    op.drop_table("team")
    op.drop_table("referee")
    op.drop_table("player")
    op.drop_table("model_version")
    op.drop_index(op.f("ix_ingestion_run_data_source_id"), table_name="ingestion_run")
    op.drop_table("ingestion_run")
    op.drop_table("data_source")
    op.drop_table("competition")
    # ### end Alembic commands ###
