"""odds and bets

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-13 13:36:45.813736

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "odds_snapshot",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("bookmaker", sa.String(length=50), nullable=False),
        sa.Column("market", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("snapshot_taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_odds_snapshot_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshot")),
        sa.UniqueConstraint(
            "match_id",
            "bookmaker",
            "market",
            "outcome",
            "snapshot_taken_at",
            name="uq_odds_snapshot_natural",
        ),
    )
    op.create_index(
        "ix_odds_snapshot_match_market",
        "odds_snapshot",
        ["match_id", "market"],
        unique=False,
    )
    op.create_table(
        "value_bet",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("model_version_id", sa.UUID(), nullable=False),
        sa.Column("market", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=False),
        sa.Column("bookmaker", sa.String(length=50), nullable=False),
        sa.Column("our_prob", sa.Float(), nullable=False),
        sa.Column("market_prob", sa.Float(), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("edge", sa.Float(), nullable=False),
        sa.Column("kelly_fraction", sa.Float(), nullable=False),
        sa.Column("suggested_stake_units", sa.Float(), nullable=False),
        sa.Column("found_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closing_decimal_odds", sa.Float(), nullable=True),
        sa.Column("closing_clv", sa.Float(), nullable=True),
        sa.Column("outcome_realised", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_value_bet_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_version.id"],
            name=op.f("fk_value_bet_model_version_id_model_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_value_bet")),
    )
    op.create_index("ix_value_bet_match", "value_bet", ["match_id"], unique=False)
    op.create_index("ix_value_bet_model", "value_bet", ["model_version_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_value_bet_model", table_name="value_bet")
    op.drop_index("ix_value_bet_match", table_name="value_bet")
    op.drop_table("value_bet")
    op.drop_index("ix_odds_snapshot_match_market", table_name="odds_snapshot")
    op.drop_table("odds_snapshot")
    # ### end Alembic commands ###
